steps:
  - label: ":computer: run tests"
    commands:
      - CI=true npm test -- --coverage &> test_results
    agents:
      queue: default
    artifact_paths:
      - test_results

  - wait: ~
    continue_on_failure: false

  - name: ':package: Build'
    commands:
      - npm run build
      - zip -r build.zip build
    agents:
      queue: default
    artifact_paths:
      - "build.zip"

  - wait: ~
    continue_on_failure: false

  - name: ':desert_island: Deploy'
    commands:
      - ls
    agents:
      queue: default
