steps:
  - label: ":computer: run tests"
    commands:
      - "sh .buildkite/scripts/tests.sh"
    agents:
      queue: default
    artifact_paths:
      - test_results

  - wait: ~
    continue_on_failure: false

  - name: ':package: Build'
    commands:
      - "sh .buildkite/scripts/build.sh"
    agents:
      queue: default
    artifact_paths:
      - "build.zip"

  - wait: ~
    continue_on_failure: false

  - name: ':desert_island: Deploy'
    commands:
      - "sh .buildkite/scripts/deploy.sh"
    agents:
      queue: default
